<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Emgu.CV" Version="4.13.0.5924" />
    <PackageReference Include="Emgu.CV.Bitmap" Version="4.13.0.5924" />
    <PackageReference Include="Emgu.CV.runtime.windows" Version="4.13.0.5924" />
  </ItemGroup>

<ItemGroup>
  <None Update="haarcascades\haarcascade_frontalface_default.xml">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
  <None Update="haarcascade_frontalface_default.xml">
    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
  </None>
</ItemGroup>

</Project>